server:
  port: 9393
management:
  contextPath: /management
spring:
  main:
    show_banner: false
  application:
    name: spring-cloud-dataflow-admin
  cloud:
    dataflow:
      yarn:
        version: "@project.version@"
    