server:
  port: 8765
spring:
  application:
    name: zuulserver
info:
  component: Zuul Server
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
  regexMapper:
    enabled: true
    servicePattern: "(?<type>^.+)-(?<group>.+)-(?<label>.+$)"
    routePattern: "${type}/${group}/${label}"
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
